# Site settings
title: Pam Griffith
email: pam@pamgriffith.net
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pamgriffith.net" # the base hostname & protocol for your site

encoding: utf-8
permalink: "/blog/:title"

gems:
  - jekyll-archives

# Build settings
markdown: kramdown

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Archive pages
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    year: 'year-archive'
    tag: 'tag-cat-archive'
    category: 'tag-cat-archive'
  permalinks:
    year: '/blog/archive/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'