# Site settings
title: Pam Griffith
email: pam@pamgriffith.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pamgriffith.net" # the base hostname & protocol for your site
twitter_username: haloedrain
github_username:  pamgriffith

encoding: utf-8
permalink: "/blog/:title"

gems:
  - jekyll-archives

# Build settings
markdown: kramdown

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Archive pages
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    year: 'year-archive'
    tag: 'tag-cat-archive'
    category: 'tag-cat-archive'
  permalinks:
    year: '/blog/archive/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'